### ISSUE TITLE
done is not a function

### ISSUE THREAD

**Issue by seep** [hughsk/glslify-import#1]
I think I'm missing something completely obvious but I'm getting an error on https://github.com/hughsk/glslify-import/blob/master/index.js#L45 that done is not a function. My build statement is:

`budo index.js --live -- -t [ babelify --optional runtime ] -t glslify -t glslify-import`

And my import statement is:

`#pragma glslify: import('./shader-chunk-lambert-vert.glsl')`

Should glslify-import be provided as a transform for glslify instead of browsrify? How would I go about that?

**Comment by hughsk** [comment]
Yeah, glslify-import should be a transform for glslify instead of browserify :) Have you tried this?

``` bash
budo index.js --live -t [ babelify --optional runtime ] -t [ glslify -t glslify-import ]
```

**Comment by seep** [comment]
Ah, thank you. I had to tweak it a little, `-t` wasn't being recognized for some reason. The working command is

`budo index.js --live -- -t [ babelify --optional runtime ] -t [ glslify --transform glslify-import ]`

Thanks for the help!
