### ISSUE TITLE
Not recursive

### ISSUE THREAD

**Issue by gregtatum** [hughsk/glslify-import#2]
This module doesn't appear to be recursive with further glslify commands that are imported. I have some command line stuff set up to fix it in my case right now, but it would be nice if it continued down into the imported files. Not sure how feasible that is with the architecture of glslify.

If this wouldn't work I could send in a PR with a small explanation on the readme mentioning this.

**Comment by hughsk** [comment]
Ah! Easily fixed I think, will take a quick look :)

**Comment by hughsk** [comment]
This should work as of `glslify-import@2.0.0` 😁

**Comment by gregtatum** [comment]
woop woop! thanks!
